-- create table patients(
-- 	id int generated by default as identity primary key,
-- 	name varchar(50) not null,
-- 	surname varchar(50) not null,
-- 	patronymic varchar(50) not null,
-- 	passport_series int not null unique,
-- 	passport_number int not null unique,
-- 	date_of_birth date not null,
-- 	phone_number varchar(12),
-- 	email varchar(100) not null unique,
-- 	password_hash text not null
-- )

-- create table doctors(
-- 	id int generated by default as identity primary key,
-- 	name varchar(50) not null,
-- 	surname varchar(50) not null,
-- 	patronymic varchar(50) not null,
-- 	position varchar(50) not null,
-- 	date_of_birth date not null,
-- 	email varchar(100) not null unique,
-- 	password_hash text not null
-- )

-- create table diseases(
-- 	id int generated by default as identity primary key,
-- 	name varchar(100) not null,
-- 	date_start date not null,
-- 	date_end date,
-- 	treatment text not null,
	
-- 	constraint ck_diseases_date_start check(date_start < date_end and date_start <= CURRENT_DATE)
-- )

-- create table tests(
-- 	id int generated by default as identity primary key,
-- 	name varchar(100) not null,
-- 	date date not null,
-- 	time time not null,
-- 	status varchar(30) not null,
-- 	result varchar(100),
-- 	patient_id int not null,
	
-- 	constraint fk_tests_patient_id foreign key (patient_id) references patients(id)
-- )


-- create table shifts(
-- 	id int generated by default as identity primary key,
-- 	date date not null,
-- 	time_start time not null,
-- 	time_end time not null,
-- 	lunch_time time not null,
-- 	doctor_id int not null,
	
-- 	constraint fk_shifts_doctor_id foreign key (doctor_id) references doctors(id)
-- )

-- create table prescriptions(
-- 	id int generated by default as identity primary key,
-- 	name varchar(50) not null,
-- 	issued_at date not null,
-- 	expired_at date not null,
-- 	patient_id int not null,
-- 	doctor_id int not null,
	
-- 	constraint fk_prescriptions_patient_id foreign key (patient_id) references patients(id),
-- 	constraint fk_prescriptions_doctor_id foreign key (doctor_id) references doctors(id)
-- )

-- create table appointments(
-- 	id int generated by default as identity primary key,
-- 	date date not null,
-- 	time time not null,
-- 	status varchar(30) not  null,
-- 	reason varchar(30) not null,
-- 	diagnose varchar(100) not null,
-- 	drugs text,
-- 	doctor_notes text,
-- 	patient_id int not null,
-- 	doctor_id int not null,
-- 	disease_id int not null,
	
-- 	constraint fk_appointments_patient_id foreign key (patient_id) references patients(id),
-- 	constraint fk_appointments_doctor_id foreign key (doctor_id) references doctors(id),
-- 	constraint fk_appointments_disease_id foreign key (disease_id) references diseases(id),
-- 	constraint ck_pointments_status check(status = 'запланирован' or status = 'отменён' or status = 'завершён'),
-- 	constraint ck_pointments_reason check(reason = 'консультация' or reason = 'повторный')
-- )

-- alter table patients
-- add constraint ck_patients_passport_series check(length(passport_series::text) = 4);

-- alter table patients
-- add constraint ck_patients_passport_number check(length(passport_number::text) = 6);

-- alter table doctors
-- alter column password_hash type text;

-- insert into patients (surname, name, patronymic, passport_series, passport_number, date_of_birth, phone_number, email, password_hash)
-- values ('Губин', 'Егор', 'Вячеславович', 1234, 654321, '01-01-2003', '89076323432', 'wserger.reger@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG')
-- insert into patients (surname, name, patronymic, passport_series, passport_number, date_of_birth, phone_number, email, password_hash)
-- values ('Ечин', 'Илья', 'Валериевич', 4321, 123456, '12-11-2003', '89076323432', 'drgb.rgvra@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');
-- insert into patients (surname, name, patronymic, passport_series, passport_number, date_of_birth, phone_number, email, password_hash)
-- values ('Ли', 'Роман', 'Владиславович', 6543, 217890, '25-05-2002', '89076323432', 'tumyum.tumnd@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');
-- insert into patients (surname, name, patronymic, passport_series, passport_number, date_of_birth, phone_number, email, password_hash)
-- values ('Фёдоров', 'Степан', 'Николаевич', 9876, 543210, '15-02-2004', '89076323432', 'EWFRBRA.gtrnh@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');
-- insert into patients (surname, name, patronymic, passport_series, passport_number, date_of_birth, phone_number, email, password_hash)
-- values ('Тарасова', 'Софья', 'Андреевна', 1203, 240506, '23-12-2003', '89076323432', 'kjvra.ruughr@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');

-- insert into doctors (surname, name, patronymic, position, date_of_birth, email, password_hash)
-- values ('Сенин', 'Артём', 'Романович', 'Врач-уролог', '23-12-1996', 'tkjbsfg.fkdobgjb@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');

-- insert into doctors (surname, name, patronymic, position, date_of_birth, email, password_hash)
-- values ('Петроченков', 'Игорь', 'Сергеевич', 'Врач-кардиолог', '12-11-1990', 'hdbvdlf.kjfrfbdh@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');

-- insert into doctors (surname, name, patronymic, position, date_of_birth, email, password_hash)
-- values ('Гладышев', 'Даниил', 'Петрович', 'Врач-проктолог', '05-05-1995', 'kjrghd.RHGSBLBV@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');

-- insert into doctors (surname, name, patronymic, position, date_of_birth, email, password_hash)
-- values ('Иванов', 'Роман', 'Владимирович', 'Врач-оторинолоринголог', '20-12-1999', 'rkejjgbvf.erthttjkjnj@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');

-- insert into doctors (surname, name, patronymic, position, date_of_birth, email, password_hash)
-- values ('Ткаченко', 'Павел', 'Дмитриевич', 'Врач-терапевт', '09-11-1996', 'rweghnbljrjtnb.fnllrfdbnjdfk@mail.ru', 'febliufga&^87yehgfOR7>KEUGHFO*&#FGVuiegp874gfelBI*&$#YG');



-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Простатит', '13-12-2019', '24-03-2020', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Бронхит', '01-12-2018', '14-12-2018', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Грипп', '05-10-2024', NULL, 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Миопия', '13-12-2020', null, 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Миопия', '13-12-2020', null, 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into diseases (name, date_start, date_end, treatment)
-- values ('Пневмония', '13-09-2023', '09-10-2023', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);');

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Полный анализ крови', '13-09-2023', '10:00:00', 'завершён', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);', 1);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Флюорография', '12-10-2023', '09:00:00', 'завершён', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);', 1);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Флюорография', '12-11-2024', '09:00:00', 'запланирован', null, 2);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Флюорография', '04-11-2024', '12:00:00', 'готовится', null, 2);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Анализ мочи', '02-11-2024', '08:00:00', 'завершён', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);', 3);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Флюорография', '15-11-2024', '09:00:00', 'отменён', null, 3);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Рентген плечевого сустава', '10-11-2024', '09:30:00', 'запланирован', null, 4);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Флюорография', '03-11-2024', '13:30:00', 'готовится', null, 4);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('МРТ сосудов шеи', '12-11-2024', '15:45:00', 'запланирован', null, 5);


-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Электрокардиограмма', '05-05-2024', '12:20:00', 'готовится', 'Что то там на врачебном; пилюли там всякие; возможно даже свечки(и так ясно какие);', 5);

-- insert into tests (name, date, time, status, result, patient_id)
-- values ('Рентген носовых пазух', '11-09-2024', '07:00:00', 'отменён', null, 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('08-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('08-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('08-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('08-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('08-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('09-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('09-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('09-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('09-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('09-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('10-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('10-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('10-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('10-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('10-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('11-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('11-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('11-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('11-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('11-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('12-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('12-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('12-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('12-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('12-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('13-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('13-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('13-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('13-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('13-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('14-11-2024', '08:00:00', '17:00:00', '13:30:00', 1);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('14-11-2024', '09:00:00', '18:00:00', '14:00:00', 2);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('14-11-2024', '08:00:00', '17:00:00', '13:00:00', 3);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('14-11-2024', '08:00:00', '17:00:00', '13:30:00', 4);

-- insert into shifts (date, time_start, time_end, lunch_time, doctor_id)
-- values ('14-11-2024', '10:00:00', '19:00:00', '14:30:00', 5);

-- insert into prescriptions (name, issued_at, expired_at, patient_id, doctor_id)
-- values ('Левофлаксоцин', '09-10-2024', '09-11-2024', 1, 5);

-- insert into prescriptions (name, issued_at, expired_at, patient_id, doctor_id)
-- values ('Арбидол', '09-10-2024', '09-11-2024', 2, 4);

-- insert into prescriptions (name, issued_at, expired_at, patient_id, doctor_id)
-- values ('Изопринозин', '09-10-2024', '09-11-2024', 3, 3);

-- insert into prescriptions (name, issued_at, expired_at, patient_id, doctor_id)
-- values ('Эвалак-форте', '09-10-2024', '09-11-2024', 4, 2);

-- insert into prescriptions (name, issued_at, expired_at, patient_id, doctor_id)
-- values ('Доктор-мом', '09-10-2024', '09-11-2024', 5, 1);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('01-12-2018', '09:10:00', 'завершён', 'консультация', 'Ну, помянем, пора жить на полную катушку', 'Левофлаксоцин', 'Что то на врачебном', 1, 5, 3);
-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('07-12-2018', '09:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Витамин Ц', 'Что то на врачебном', 1, 5, 3);
-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('14-12-2018', '10:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Витамин Ц', 'Что то на врачебном', 1, 5, 3);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('13-12-2020', '09:10:00', 'завершён', 'консультация', 'Ну, помянем, пора жить на полную катушку', 'Глазные капли', 'Что то на врачебном', 2, 4, 5);
-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('11-04-2021', '09:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Глазные капли', 'Что то на врачебном', 2, 4, 5);
-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('23-10-2021', '10:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Глазные капли', 'Что то на врачебном', 2, 4, 5);


-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('09-10-2024', '10:00:00', 'завершён', 'консультация', 'Ну, помянем, пора жить на полную катушку', 'Изопринозин', 'Что то на врачебном', 3, 3, 5);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('13-09-2023', '09:00:00', 'завершён', 'консультация', 'Ну, помянем, пора жить на полную катушку', 'Эвалак-форте', 'Что то на врачебном', 4, 2, 7);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('20-09-2023', '10:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Витамин Ц', 'Что то на врачебном', 4, 2, 7);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('27-09-2023', '10:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Витамин Ц', 'Что то на врачебном', 4, 2, 7);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('09-10-2023', '09:00:00', 'завершён', 'повторный', 'Ну, помянем, пора жить на полную катушку', 'Витамин Ц', 'Что то на врачебном', 4, 2, 7);

-- insert into appointments (date, time, status, reason, diagnose, drugs, doctor_notes, patient_id, doctor_id, disease_id)
-- values ('13-12-2019', '10:00:00', 'завершён', 'консультация', 'Ну, помянем, пора жить на полную катушку', 'Доктор-мом', 'Что то на врачебном', 5, 1, 1);

